version: 0.2

env:
  parameter-store:
    API_KEY: /kevin-bacon/API_KEY

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install
  pre_build:
    commands:
      - echo API_KEY=$API_KEY >> .env
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  base-directory: dist
